const stages=['opening','balloons','missing','gifts'];const reveal=document.querySelector('#reveal'),body=document.querySelector('#reveal-body'),confirmBox=document.querySelector('#confirm');let pendingGift=0;
function go(id){stages.forEach(s=>document.getElementById(s).classList.toggle('active',s===id));document.querySelector('#chapter').textContent=String(stages.indexOf(id)+1).padStart(2,'0')+' / 04';window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
document.querySelectorAll('.next').forEach(b=>b.addEventListener('click',()=>{startMusic();go(b.dataset.next)}));document.querySelector('#restart').onclick=()=>go('opening');
const balloons=[['1(1).jpeg','Your grace','There is a quiet magic in the way you carry yourself. You make even the simplest moment feel beautiful.','#f6b8c5','#c97392'],['2.jpeg','Your smile','Your smile is my favourite kind of sunshine. I hope you always know how lovely you are.','#f2c5a9','#cc806f'],['4.jpeg','Your sparkle','You bring colour into my world just by being you. I could look at you and smile for hours.','#d5b7ef','#9875be'],['6.jpeg','Your light','Every room feels warmer with you in it. Your presence is a gift I never take for granted.','#b8ded6','#6baaa5'],['flowers.jpeg','My favourite person','In every version of my future, I hope to find you there, smiling back at me.','#f3b8d6','#b6679c'],['3.jpeg','Little moments','It is the little moments with you that become my biggest, most precious memories.','#f3d1a8','#c89170'],['5.jpeg','Your heart','I love the tenderness in your heart and the beautiful person you are, inside and out.','#c3c9f1','#838dc6'],['8.jpeg','Just you','You do not have to do anything extraordinary to make my day. Being you is more than enough.','#d9b5d9','#a772aa'],['9.jpeg','Always us','If I had to choose my favourite thought, it would always be a future with you.','#eeaea9','#ba6d76']];
const grid=document.querySelector('#balloon-grid');balloons.forEach((b,i)=>{const el=document.createElement('button');el.className='balloon';el.style.cssText=`--light:${b[3]};--dark:${b[4]};--delay:${(i%5)*-.4}s`;el.setAttribute('aria-label','Open balloon '+(i+1)+': '+b[1]);el.innerHTML=`<span class="balloon-shape">${i+1}</span><span class="string"></span><span class="balloon-label">Tap to reveal ♡</span>`;el.onclick=e=>{body.innerHTML=`<img src="assets/${b[0]}" alt="A beautiful photograph of Aparna"><h3>${b[1]}</h3><p>${b[2]}</p>`;reveal.showModal();burst(e)};grid.append(el)});
const gifts=[{title:'A note for you',sub:'The words I always mean',icon:'💌',html:'<span class="big-heart">♥</span><h3>My sweetest hello</h3><p>If today has been a long day, let this be a reminder: somewhere, someone is thinking of you with the biggest smile. That someone is me. I love you more than these little words can hold.</p>'},{title:'Our memory',sub:'A moment I will keep',icon:'📸',html:'<img src="assets/7.jpeg" alt="One of our beautiful memories together"><h3>A moment with you</h3><p>Every picture of us is a little time machine. It takes me right back to how lucky I felt standing beside you. Here is to all the memories we have yet to make.</p>'},{title:'A love letter',sub:'Open and read slowly',icon:'📜',html:'<h3>To my Aparna</h3><div class="letter"><p>My love,</p><p>You have become the person I want to share all my little stories with, the first person I think of when something wonderful happens, and the one I miss in the quiet moments.</p><p>I cannot promise that every day will be perfect. I can promise to keep choosing you, to listen, to care, and to try to make you smile. Thank you for being you and for letting me be a part of your story.</p><p>With all my love,<br>Sonu ♡</p></div>'},{title:'My forever wish',sub:'One last surprise',icon:'🎁',html:'<span class="big-heart">♥</span><h3>My wish is you</h3><p>More walks together. More silly conversations. More photographs. More of your smile across from mine. Whatever life brings, I want to keep making our little world beautiful together.</p><p><strong>I love you, Aparna. Today, tomorrow, and all the days after. ❤️</strong></p>'}];
const giftGrid=document.querySelector('#gift-grid');gifts.forEach((g,i)=>{let el=document.createElement('button');el.className='gift';el.innerHTML=`<span class="gift-icon">${g.icon}</span><strong>${g.title}</strong><small>${g.sub} · Tap to open</small>`;el.onclick=()=>{pendingGift=i;confirmBox.showModal()};giftGrid.append(el)});document.querySelector('#yes').onclick=e=>{confirmBox.close();body.innerHTML=gifts[pendingGift].html;reveal.showModal();burst(e)};document.querySelector('#close').onclick=()=>reveal.close();document.querySelector('#confirm-close').onclick=()=>confirmBox.close();
function burst(e){const r=e.currentTarget.getBoundingClientRect();for(let i=0;i<16;i++){const x=document.createElement('span');x.className='spark';x.textContent=i%3?'♥':'✦';x.style.left=(r.left+r.width/2)+'px';x.style.top=(r.top+r.height/2)+'px';x.style.color=i%2?'#f7b8ca':'#fff3d6';x.style.setProperty('--x',((Math.random()-.5)*260)+'px');x.style.setProperty('--y',((Math.random()-.5)*260)+'px');document.body.append(x);setTimeout(()=>x.remove(),1000)}}
const petals=document.querySelector('.petals');for(let i=0;i<14;i++){let p=document.createElement('span');p.className='petal';p.textContent=i%3?'♡':'✦';p.style.left=(Math.random()*100)+'%';p.style.animationDuration=(10+Math.random()*12)+'s';p.style.animationDelay=(-Math.random()*20)+'s';p.style.fontSize=(10+Math.random()*13)+'px';petals.append(p)}
// A small original instrumental loop synthesized locally: no external music file or network dependency.
let ctx,master,playing=false,timer,nextNote=0,noteIndex=0;const music=document.querySelector('#music');const melody=[330,392,440,392,294,330,392,330,262,330,392,330,294,262,247,294];const chords=[[220,277,330],[196,247,294],[174.6,220,262],[196,247,294]];
function tone(freq,time,duration,volume,type='sine'){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,time);gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(volume,time+.035);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain).connect(master);osc.start(time);osc.stop(time+duration+.02)}
function schedule(){while(nextNote<ctx.currentTime+.3){let i=noteIndex%melody.length; tone(melody[i],nextNote,.75,.095);if(i%4===0)chords[Math.floor(i/4)].forEach((n,j)=>tone(n/2,nextNote+j*.08,1.7,.045,'triangle'));noteIndex++;nextNote+=.48}}
function startMusic(){if(playing)return;try{ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();ctx.resume();master=master||ctx.createGain();master.gain.value=.6;master.connect(ctx.destination);nextNote=ctx.currentTime+.05;timer=setInterval(schedule,100);playing=true;music.innerHTML='♫ <span>Music on</span>';music.setAttribute('aria-label','Turn music off');music.setAttribute('aria-pressed','true')}catch{music.disabled=true}}
music.onclick=()=>{if(!playing){startMusic()}else{clearInterval(timer);ctx.suspend();playing=false;music.innerHTML='♫ <span>Music off</span>';music.setAttribute('aria-label','Turn music on');music.setAttribute('aria-pressed','false')}};
const initial=location.hash.slice(1);if(stages.includes(initial))go(initial);
